### ISSUE TITLE
C#/C++ language filters are lost after pagination

### ISSUE THREAD

**Issue by fmoliveira** [deleteman/lfpr#55]
After pagination in the find projects page, the language filter value is changed to C if you've selected C#, or if you've selected C++ it's lost, changing it back to All.

Steps to reproduce:
1. Go to "Find projects" page
2. In the filters, select Language: C# and press the Filter button.
3. C# repos will be displayed in the first page. Now, browse to the next page.
4. The "C#" value is still in the query string, but all the results shown are for C language. Also, the filter combo box has its value changed to "C".
5. Back to step 2 and now select C++ as the language filter. A similar issue will occur, displaying C results in the next page and changing combo box value to "All".

**Comment by rich-ard** [comment]
Doing testing on a fix now, should have it checked out and ready in the next day or two

**Comment by rich-ard** [comment]
Pull request submitted.

**Comment by deleteman** [comment]
@rich-ard thanks for the PR, but this is not really fixed. If you click on the prev page link after you go to page 2, you end up filtering by C, not C#.

**Comment by rich-ard** [comment]
Ah - I've fixed it for searches run directly from the "search" bar on the main page, and pages that follow therefrom; looks like a similar fix is needed for the pages searched from the "find projects" page. On it - might want to consider combining these features, though, as that means there are two places similar functions are being run.

**Comment by rich-ard** [comment]
Aaaaand pull request submitted.

**Comment by deleteman** [comment]
@rich-ard awesome! I'll be reviewing it in the following days.
Regarding your refactoring advise, I do agree, but I have to admit I want to re-write the entire site, in Node, to be honest PHP is not doing it for me anymore,and the site has a lot of issues, especially regarding stats gathering, that I think need a serious re-write in order to get them right.
So once I'm out of my current, more time consuming side projects (writing two books right now) I'll probably start tinkering with a new version of the site.

**Comment by rich-ard** [comment]
Right on. Good to know, too, as I was considering attacking some of the PDO
needs.

**Comment by fmoliveira** [comment]
Good to know @deleteman . Count on me when rewriting the website in Node. :+1:

**Comment by fmoliveira** [comment]
Thank you @rich-ard for the good job! :)

Good to know @deleteman, and I know what are you talking about. I'm also tired of PHP. Count on me when rewriting the website in Node. :+1:

**Comment by fmoliveira** [comment]
Closing as stale.
